[package]
name = "kdbx"
version = "0.1.0"
authors = ["Wu Yu Wei <wusyong9104@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keepass = "0.4"